### PR TITLE
DSD-635:  Updated GA lint job

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-635](https://jira.nypl.org/browse/DSD-635)

## This PR does the following:

- Updates the Github Actions lint job to use the `npm run lint` command which internally runs the TSDX lint script. Seems to be working now that one specific file is fixed and might've been issues with a previous version of eslint/prettier.

## How has this been tested?

Github Command runs and passes.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr830-pmfzfinzyon4kezkur6wdhysh46tauc0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d6030bdc579fc65d8e8ae8

**Review by bigfishdesign13 — APPROVED** [review]
Sure.

**Pull request merged**
