### PR TITLE
Move tests

### LINKED ISSUE #188: Integrate tests with their corresponding components

### PR DESCRIPTION
**Pull request by helenvholmes**
Closes #188.

## **This PR does the following:**
- Moves tests for components into their corresponding component folders

### Review:
- [ ] Run `npm run test` in `src/react-components/`

### CODE REVIEW

**Comment by hokei** [comment]
@M0nica @scooooooooby does anyone have a preference of `component-test.tsx` vs `component.test.tsx` ? 
I think I prefer `component.test.ts` and I'm not sure why it was named like this in the first place.  Since all the test files are touched, let's use this opportunity to rename the test file names?

**Comment by helenvholmes** [comment]
@hokei I'm certainly fine with the latter, I do think it looks cleaner—although I couldn't tell you why. I can make the update.

**Comment by helenvholmes** [comment]
Well, one neat thing I've realized... VSCode (or maybe my theme?) will update its lil'icon when you do so:

Screen Shot 2020-06-03 at 9 56 44 AM

**Comment by hokei** [comment]
honestly the changed icon is 99% of the reason why I want to do it.

**Comment by helenvholmes** [comment]
@hokei we are 3000% on the same page 😂

**Review by hokei — APPROVED** [review]

**Comment by hokei** [comment]
remember changelog update

**Pull request merged**
