### PR TITLE
DSD-624: Adding additionalStyles prop to Breadcrumbs

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-624](https://jira.nypl.org/browse/DSD-624)

## This PR does the following:
- Adds `additionalStyles` prop to the `Breadcrumbs` component.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr783-fntoswfujfcjviq9uq6fbdwoeckiuz12.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a69002aee91cfa02c18f04

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
The `Latest Version` version number needs to be updated to `0.25.4`.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr783-fntoswfujfcjviq9uq6fbdwoeckiuz12.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a69002aee91cfa02c18f04

**Review by bigfishdesign13 — APPROVED** [review]
Spot on.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr783-fntoswfujfcjviq9uq6fbdwoeckiuz12.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a69002aee91cfa02c18f04

**Pull request merged**
