### PR TITLE
Add `attributes` to `SearchBar` form

### PR DESCRIPTION
**Pull request by siberry**
Fixes JIRA ticket [DSD-112](https://jira.nypl.org/browse/DSD-112)

## **This PR does the following:**
- The `SearchBar` accepts an `attributes` prop, but it is currently not being implemented. Seems like a small oversight. I need to use it for SCC to add `method` and `action` attributes, which are on existing SCC search bar.

### Front End Review:
- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Can you create a bug ticket in the DSD board and link it in the description? Just so your contribution is also on the JIRA board.

This is fine but `method` and `action` are actual `form` element attributes that I would prefer to be directly passed rather than in an `attributes` object. How do others feel about this? This is not a blocker for this PR.

**Comment by hokei** [comment]
I agree with Edwin - `attributes` is a fallback we're using for people who need stuff quickly, we can totally keep it but if there are specific form props that you need, let's put them here explicitly

**Comment by siberry** [comment]
Added `method` and `action` to `SearchBar` as well! Thanks for the suggestions. Also ticket here: https://jira.nypl.org/browse/DSD-112

**Review by kaplanmichael — APPROVED** [review]
Good to go! 😄

**Pull request merged**
