### PR TITLE
DSD-701: Removing the Input and CardEdition components

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-701](https://jira.nypl.org/browse/DSD-701)

## This PR does the following:

- Removes the `CardEdition` and `Input` components.
- Updates how the `SearchBar` is implemented in the "Bidirectionality" doc.
- Updates the "Autosuggest" guide with `TextInput`.

## How has this been tested?

Running tests, the build script, and running storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr837-fbchfn84o3uzgscrwc2kice8yscnt5pl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d8aa3b5f46ed13d8fd534f

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr837-fbchfn84o3uzgscrwc2kice8yscnt5pl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d8aa3b5f46ed13d8fd534f

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr837-fbchfn84o3uzgscrwc2kice8yscnt5pl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d8aa3b5f46ed13d8fd534f

**Pull request merged**
