### PR TITLE
DSD-947: Enum to string literal values

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-947](https://jira.nypl.org/browse/DSD-947)

## This PR does the following:

- Removes all enums and replaces them with string literal types. This includes: `AccordionType`, `BreadcrumbsTypes`, `ButtonTypes`, `DatePickerTypes`, `FormGaps` (deleted), `GridGaps`, `HeadingSizes`, `HeadingLevels`, `HeroTypes`, `IconAlign`, `IconTypes`, `IconRotationTypes`, `IconColors`, `IconSizes`, `IconNames`, `LinkTypes`, `ListTypes`, `LogoColors`, `LogoSizes`, `LogoNames`, `NotificationTypes`, `SelectTypes`, `LabelPositions`, `SkeletonLoaderImageRatios`, `StatusBadgeTypes`, `StructuredContentImagePosition`, `TextSizes`, `TextInputTypes`, `TextInputFormats`, `TextInputVariants`, `ToggleSizes`, `VideoPlayerTypes`, `VideoPlayerAspectRatios`, and `LayoutTypes`.
- Removes `getVariant` and `getStorybookEnumValues` helper functions.
- Minor Storybook updates to get the right values to display. Note: The `gap` prop doesn't display its comment because it's also a Chakra-based prop. We'll have to find a way around this.

This means that we go from 
```
import { Heading, HeadingSizes } from "@nypl/design-system-react-components";

<Heading size={HeadingSizes.Secondary}>Text</Heading>
```

to
```
import { Heading } from "@nypl/design-system-react-components";

<Heading size="secondary">Text</Heading>
```

This applies to ALL components and ALL props.

## How has this been tested?

Storybook

## Accessibility concerns or updates

- N/A, the changes are only internal but nothing has changed visually or functionally.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Review by nypl-wluisi — COMMENTED** [review]
@EdwinGuzman Testing this out in Scout app. Everything looks good so far. A few things I noticed.

Seems like any use of Card with a custom image component, even if you don't add a prop for `aspectRatio` will return this console msg:

_"NYPL Reservoir Card: Both the `imageProps.component` and `imageProps.aspectRatio` props were set but `imageProps.aspectRatio` will be ignored in favor of the aspect ratio on `imageProps.component` prop."_

Another small issue I noticed is on the `Icon` component, the color prop allows any value to be set, even in .tsx files.

For example, this shouldn't be allowed, but build works and eslint doesn't pick it up

```jsx
<Icon
  align="left"
  name="search"
  size="medium"
  color="section.whats-on.primary2222"
/>
```

Whereas `name` prop for example, this correctly gets picked up by linter and also the build will fail
```jsx
<Icon
  align="left"
  name="search1234"
  size="medium"
  color="section.whats-on.primary"
/>
```

**Comment by nypl-wluisi** [comment]
Not related to the changes on this PR, but I'm able to suppress the console.warn _"Both the imageProps.component and imageProps.aspectRatio props ..."_ by setting `aspectRatio: "square"`, i.e.,

```jsx
<Card
  . . . other props
  imageProps: {
    component: image,
    aspectRatio: "square",
  }
/>
```

**Review by nypl-wluisi — APPROVED** [review]
@EdwinGuzman @bigfishdesign13 I've tested this pretty extensively in Scout app yesterday. Everything looks great! Only small issues I found were the ones mentioned in this comment: https://github.com/NYPL/nypl-design-system/pull/976#pullrequestreview-957011272

The Card issues are not related to this PR. The `Icon` component `color` prop issue I'm not sure if it's related to the updates here, but for me is not a show stopper.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Comment by EdwinGuzman** [comment]
> For example, this shouldn't be allowed, but build works and eslint doesn't pick it up
>
> ```
>   <Icon
>     align="left"
>    name="search"
>    size="medium"
>    color="section.whats-on.primary2222"
>  />
> ```
> Whereas name prop for example, this correctly gets picked up by linter and also the build will fail
> ```
>  <Icon
>    align="left"
>    name="search1234"
>    size="medium"
>    color="section.whats-on.primary"
>  />
> ```

So this happens because a prop like `name` is specific and custom to the created `Icon` component and is not a style prop from Chakra. `color`, however, is a style prop from Chakra that other components also use. Like you saw, it allows any string because (maybe?) there's more configuration needed to override the Chakra's initial settings. I haven't found much yet and it's also an issue when storybook build.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr976-fxa9fo8qdnzzszw0t5hcspea0ovp43nl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6269ad8c2e91387b1794dd72

**Pull request merged**
