### PR TITLE
DSD-386: Three examples of snapshot testing

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-386](https://jira.nypl.org/browse/DSD-386)

## This PR does the following:
- This adds three examples of snapshot testing through jest.
- To see an error, the easiest way is to update `Notification.tsx` and update the `<aside>` to `<div>`s and then run `npm test`. You'll see the failure and error message.
- These are just examples of how we can add more tests to make sure that the DOM is what we expect and that changes are intended.
- Snapshot files should be committed so don't forget to add them. They automatically get generated.
- Each snapshot test includes further instructions at the top of the file (including how to update tests).
- Part of the ticket was to add `jest-axe` but I prematurely added it to PR #619 .

## How has this been tested?

Locally.

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 added a section to the README on snapshot testing.

**Review by bigfishdesign13 — APPROVED** [review]
This looks good to me.

**Comment by hokei** [comment]
This is really great!  My outstanding question is around when someone would use a snapshot test -- because this is a component library and the visuals matter here, should all components have a snapshot test so we're alerted when something changes?

**Comment by EdwinGuzman** [comment]
We wouldn't have a snapshot test for components are that more like guidelines, such as the `Autosuggest`, but yes, if we can get snapshot tests on every component where we expect a specific UI (including with different props), that'd be great.

**Review by hokei — APPROVED** [review]

**Pull request merged**
