### PR TITLE
DSD-924 - Change caption and credit text from margin-bottom to margin…

### PR DESCRIPTION
**Pull request by knezmilos**
Fixes JIRA ticket DSD-924

## This PR does the following:

- Change caption and credit text from margin-bottom to margin-top

## How has this been tested?

Storybook

## Accessibility concerns or updates

N/A

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr982-sosbhdf4d8kvsyuxdz2mbxklkxrswj8p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626de99e8a4c5796e73fe86d

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
Make sure to update the CHANGELOG and to update the Latest Version number on the `Image` story page.  The Latest Version number should match the release version, which will be `0.28.0` for this update.

```
src/components/Image/Image.stories.mdx
line 85
```

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr982-sosbhdf4d8kvsyuxdz2mbxklkxrswj8p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626de99e8a4c5796e73fe86d

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Review by EdwinGuzman — APPROVED** [review]

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr982-sosbhdf4d8kvsyuxdz2mbxklkxrswj8p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626de99e8a4c5796e73fe86d

**Pull request merged**
