### PR TITLE
DSD-620: Updating the margin for sublabels in DatePicker component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-620](https://jira.nypl.org/browse/DSD-620)

## This PR does the following:
- Updates the sub-label margins to "0" for the `DatePicker` component in the "date range" state.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Note: Will fix test in a separate PR.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr784-jxiddkzi6lqcsd42bjpotcqnnqzobfnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a796f50048b8ce5278d28b

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr784-jxiddkzi6lqcsd42bjpotcqnnqzobfnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a796f50048b8ce5278d28b

**Review by bigfishdesign13 — APPROVED** [review]
This looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr784-jxiddkzi6lqcsd42bjpotcqnnqzobfnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a796f50048b8ce5278d28b

**Pull request merged**
