### PR TITLE
RENO-2068 - Design System: StatusBadge Component Updates

### PR DESCRIPTION
**Pull request by knezmilos**
Fixes #2068

## **This PR does the following:**
- Removes statusBadgeText prop to allow text to be inside component

### Front End Review:
- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
This looks good. One minor comment that doesn't need to hold this PR, if no children are passed, the component will render an empty colored bar. That's probably not what anyone wants, right? This accidental rendering won't occured with the `if (!props.children) ...` check that was deleted.

Screen Shot 2021-02-25 at 3 25 51 PM

**Comment by nypl-wluisi** [comment]
Yeah we should add this back, right? You shouldn't use this component w/o passing text inside it.

```
if (!props.children) {
  console.warn("Status Badge has no children");
}
```

@knezmilos @EdwinGuzman

**Comment by knezmilos** [comment]
The intention was to always pass text to it, but the check can be added back to be sure there's always text.  Please confirm.
@EdwinGuzman

**Comment by EdwinGuzman** [comment]
I think it'll be good to add back. What do you think @hokei @kaplanmichael ?

**Comment by kaplanmichael** [comment]
> I think it'll be good to add back. What do you think @hokei @kaplanmichael ?

Do we have a history in the DS of doing things like this to prevent undesirable output?  If so, then I agree we should handle this in a manner consistent with what we've done elsewhere.  If not, we should probably discuss as a team to what extent we want to "save DS users from themselves"...

**Comment by hokei** [comment]
In the past we've warned, and I think we can do that here - this component doesn't assume that people will be passing text from, say, an api response, but there's nothing to say it _can't_ 
In terms of "saving users from themselves" the only thing we've really settled on is that DS fail to a fallback rather than crashing the app that it's in.

**Comment by EdwinGuzman** [comment]
@knezmilos let's add that snippet back in. It won't crash the app but warn devs that something is wrong.

Since this is a component update, can you also update the changelog with a new version and changes?

**Comment by knezmilos** [comment]
@EdwinGuzman both changes are done

**Review by EdwinGuzman — APPROVED** [review]
Looks good but there are some merge conflicts.

**Review by kaplanmichael — APPROVED** [review]

**Pull request merged**
