### PR TITLE
DSD-824: HelperErrorText styling/implementation refactor

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-824](https://jira.nypl.org/browse/DSD-824)

## This PR does the following:

- Updates the styling for the `HelperErrorText` component, mostly by removing individual DS component's own use of `marginTop` for its placement.
- Updates the theme object key name of `helper` to `helperErrorText` where appropriate.
- Removes the `Box` wrapper around the `HelperErrorText` component in `Checkbox`, `CheckboxGroup`, `ComponentWrapper`, `DatePicker`, `Fieldset`, `Label`, `Radio`, `RadioGroup`, `Select`, `Slider`, `TextInput`, and `Toggle`.

@bigfishdesign13 The `marginTop` for the `HelperErrorText` is set to "xxs" for all components, but the `CheckboxGroup` and `RadioGroup` components both have their `marginTop` set to "s". I didn't change this because I wanted to run this by you but should it be set to "xxs" as well?

## How has this been tested?

Storybook. Just visually checking that the UI is the same even though the DOM has changed (the wrapper div around the `HelperErrorText` component has been removed).

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr925-ul0rf2b71hm8pfwiugd9frjflbafznos.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62446b339413e8006b35fbf3

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr925-ul0rf2b71hm8pfwiugd9frjflbafznos.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62446b339413e8006b35fbf3

**Comment by bigfishdesign13** [comment]
@EdwinGuzman,
```
@bigfishdesign13 The marginTop for the HelperErrorText is set to "xxs" for all components, but the CheckboxGroup and RadioGroup components both have their marginTop set to "s". I didn't change this because I wanted to run this by you but should it be set to "xxs" as well?
```
I debated this initially and chose to leave it at the “s” value, but looking at it now, I think we can cut it back.  However, let’s use “xs” for the group components.

**Comment by EdwinGuzman** [comment]
Updated.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr925-ul0rf2b71hm8pfwiugd9frjflbafznos.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62446b339413e8006b35fbf3

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
All `Latest Version` values need to be changed to `0.26.0`.  It also seemed that `Latest Version` was not update on some story files where it should have been.  `Checkbox` and `CheckboxGroup`, for example.

Also, and this is somewhat out or nowhere, `Toggle` should use the same pattern as `Checkbox` and `Radio` when it comes to the alignment of the helper text and the helper text should align with the label text.  When working on that, make sure to check the alignment fo rboth the `Large` and `Small` sizes.

**Comment by EdwinGuzman** [comment]
Updated.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr925-ul0rf2b71hm8pfwiugd9frjflbafznos.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62446b339413e8006b35fbf3

**Review by bigfishdesign13 — APPROVED** [review]
Yes.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr925-ul0rf2b71hm8pfwiugd9frjflbafznos.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62446b339413e8006b35fbf3

**Comment by EdwinGuzman** [comment]
@bigfishdesign13  please review this again to make sure the margins are correct in all the updated components.

**Review by bigfishdesign13 — APPROVED** [review]
Yes, the spacing for the helper text looks good in the elements that use it.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr925-ul0rf2b71hm8pfwiugd9frjflbafznos.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62446b339413e8006b35fbf3

**Pull request merged**
