### PR TITLE
Bug fix: Hiding the helper text for TextInput hidden type

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-485](https://jira.nypl.org/browse/DSD-485)

## This PR does the following:
- This addresses the bug @antlong found in ticket DSD-485. The helper text should not appear for the "hidden" type.

## How has this been tested?

Storybook and updated unit test.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr711-xlnhvmp0ic9kis61vaedruntnrvsbr66.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615739d47207f26781302ce1

**Review by bigfishdesign13 — COMMENTED** [review]
This works and it looks good.  But I wonder, when `type` is set to `hidden`, should we strip all of the extra attributes out of the input tag and only include `type`, `id`, `aria-hidden` and `value`?

**Comment by EdwinGuzman** [comment]
Good point, I'll update it.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr711-xlnhvmp0ic9kis61vaedruntnrvsbr66.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615739d47207f26781302ce1

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr711-xlnhvmp0ic9kis61vaedruntnrvsbr66.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615739d47207f26781302ce1

**Review by bigfishdesign13 — APPROVED** [review]
Very nice.

**Pull request merged**
