### PR TITLE
DSD-945: Fixing images rendered with a non-default aspectRation in a figure

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-945](https://jira.nypl.org/browse/DSD-945)

## This PR does the following:

- Fixes how `Image`s are rendered with any aspect ratio value inside a figure element (set when a caption or credit or both are set).

## How has this been tested?

Storybook with the Turbine example.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr979-o9olunzc2unyeb58ysu6cnrskjzt5xpw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626abc578a3b7b49decd2392

**Review by bigfishdesign13 — APPROVED** [review]
I pulled this into `Turbine` and the update looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr979-o9olunzc2unyeb58ysu6cnrskjzt5xpw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626abc578a3b7b49decd2392

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr979-o9olunzc2unyeb58ysu6cnrskjzt5xpw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626abc578a3b7b49decd2392

**Comment by EdwinGuzman** [comment]
Needs to wait until 1.0.0 is released before merging.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr979-o9olunzc2unyeb58ysu6cnrskjzt5xpw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/626abc578a3b7b49decd2392

**Pull request merged**
