### PR TITLE
Optionally adding an id attribute to the Input component

### LINKED ISSUE #433: Empty `id` prop renders `undefined` for `Input`
### Description of issue:
- The `id` prop is optional but it is still added to the id for the `input` element that gets rendered as `input-${id}`. But, if it's optional and no value is passed, the `Input` component renders `<input id="input-undefined" .... />`.

If there are multiple `Input` components on a page and no id values are passed to any of them, there will be duplicate id issues. Example from `react-axe`:

Screen Shot 2020-11-18 at 12 04 19 PM

Solution:
Make the `id` required.

### Component in question (if applicable):
- `Input`

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes #433 

## **This PR does the following:**
- Conditionally renders an `id` for the `Input` component. The `id` is an optional prop but if one isn't added, the `Input` component still renders an `id` as `id="input-undefined"`.

Does this update require a changelog update? It's not changing the API but it is updating what gets rendered.

Another approach I was thinking of doing was making the `id` required so it always renders an id. What do you think?

### Front End Review:
- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by helenvholmes** [comment]
> Does this update require a changelog update? It's not changing the API but it is updating what gets rendered.

I think so. I'd bump patch since it's fixing a bug fix.
 
> Another approach I was thinking of doing was making the `id` required so it always renders an id. What do you think?

Crystal and I moved away from required props at @kristojorg's suggestion over the summer... additionally this would be a more disruptive release if we went that route. I think the proposed solution you have in the PR is a good one, let's move forward with that.

**Comment by kristojorg** [comment]
Question - why not just not render the id if one isn't defined? I believe you'll get browser errors if you have multiple elements with the same ID , which would happen here if you don't pass that prop to the component right?

**Comment by EdwinGuzman** [comment]
Yes, if you don't pass in the `id` prop and have multiple `Input` components, you'd get duplicate id errors since `id-undefined ` will be used for all the components. This PR fixes that by making it so that the id isn't rendered if it is not passed in.

**Comment by kristojorg** [comment]
Ah okay I see, awesome 👍

**Review by helenvholmes — APPROVED** [review]
Looks great!

**Pull request merged**
