### PR TITLE
DSD-679: SearchBar NoBrand button

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-679](https://jira.nypl.org/browse/DSD-679)

## This PR does the following:

- Removes the `ButtonTypes.SearchBar` variant style in the `Button` component in favor of passing those styles directly to the `Button` through its `additionalStyles` prop. This allows the ability to render the `NoBrand` variant which is now toggled by the `SearchBar` component through the `noBrandButtonType` prop.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

- None, this is just styling.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr834-ehi2x9dusyorycnhcnskmf1itq0jm9g4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d75bdb5f46ed13d8f7f38d

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr834-ehi2x9dusyorycnhcnskmf1itq0jm9g4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d75bdb5f46ed13d8f7f38d

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr834-ehi2x9dusyorycnhcnskmf1itq0jm9g4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d75bdb5f46ed13d8f7f38d

**Review by bigfishdesign13 — APPROVED** [review]
This looks good.  I like that you decided to use `additionalStyles` for the the adjusted button styles and then rmeoved the variant from `Button`.

**Comment by bigfishdesign13** [comment]
@EdwinGuzman I just reazlied that references to the `SearchBar` button type need to be removed from the style guide pages.  Do you want to do that as part of this ticket before merging or should I create a new ticket?

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 I'll update this PR.

**Pull request merged**
