### PR TITLE
DSD-845: Hooks Storybook documentation & more exposed design tokens

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-845](https://jira.nypl.org/browse/DSD-845) and [DSD-722](https://jira.nypl.org/browse/DSD-722)

## This PR does the following:

- Adds Storybook documentation pages for the `useCarouselStyles`, `useNYPLTheme`, and `useWindowSize` custom hooks.
- Exports the `useCarouselStyles` and `useWindowSize` hooks.
- Moves `useNYPLTheme` documentation  from the "Chakra UI" page to its own page.
- Then worked on DSD-722 to include new typography design tokens into the `useNYPLTheme` hook and its returned style object.

## How has this been tested?

Storybook, including testing the new fontSizes and fontWeights design tokens in Charka components and HTML elements.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr931-3od93hyodw8qs9q2l0dybamfmejo87qn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62472fb3b1a46a5aa1c461fd

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr931-3od93hyodw8qs9q2l0dybamfmejo87qn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62472fb3b1a46a5aa1c461fd

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr931-3od93hyodw8qs9q2l0dybamfmejo87qn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62472fb3b1a46a5aa1c461fd

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr931-3od93hyodw8qs9q2l0dybamfmejo87qn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62472fb3b1a46a5aa1c461fd

**Pull request merged**
