### PR TITLE
DSD-461: Updating the CardLayouts enum values

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-461](https://jira.nypl.org/browse/DSD-461)

## This PR does the following:
- Updates the `Horizontal` and `Vertical` values to `Row` and `Column`.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr700-3lzizwb3qtz4omejh8upbyj9cqjrp91l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61535f82cc9cc49b5158ae54

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  Straight forward.

**Comment by bigfishdesign13** [comment]
I jumped the gun on this one.  The verbiage on the story page needs to be updated to reflect the new layout values.

For example:
`...for a vertical Card.` should become `...for a Card with a column layout.` or `...for a column Card.`

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
Please see the last comment I left regarding the language on the story page.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr700-3lzizwb3qtz4omejh8upbyj9cqjrp91l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61535f82cc9cc49b5158ae54

**Review by bigfishdesign13 — APPROVED** [review]
The updates look good!

**Pull request merged**
