### PR TITLE
DSD-603: SearchBar input props

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-603](https://jira.nypl.org/browse/DSD-603)

## This PR does the following:
- Adds additional properties that can be used in the `textInputProps` prop in the `SearchBar` component. This allows properties such as `onChange` to the passed directly to the `TextInput` which is inside the `SearchBar`.

## How has this been tested?

Storybook and there's an example on how to use it.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr769-hqy95riuslps56drqsho7hudgzpnhudh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6196681e908ae12a2c5dc4e5

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr769-hqy95riuslps56drqsho7hudgzpnhudh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6196681e908ae12a2c5dc4e5

**Review by bigfishdesign13 — APPROVED** [review]
I think this looks good.  Has this pattern been used in any of the other DS components?  Not that I can recall.

**Comment by EdwinGuzman** [comment]
No, this should be the first component where we have this pattern.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr769-hqy95riuslps56drqsho7hudgzpnhudh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6196681e908ae12a2c5dc4e5

**Pull request merged**
