### PR TITLE
Updates hero padding on primary type

### PR DESCRIPTION
**Pull request by helenvholmes**
## **This PR does the following:**
- Updates `Hero`'s primary option to have a larger top/bottom padding on the inner content via [Reno-1670](https://jira.nypl.org/browse/RENO-1670)

### Front End Review:
- [ ] View [the example in Storybook](https://deploy-preview-457--stoic-murdock-c7f044.netlify.app/?path=/story/hero--hero-primary)

### CODE REVIEW

**Comment by helenvholmes** [comment]
To give some context here, Sharon emailed me yesterday to increase the padding and Kathy identified the ticket where this work happened in Reno ([1670](https://jira.nypl.org/browse/RENO-1670)).

**Review by nypl-wluisi — COMMENTED** [review]
This looks good. Are there any small tweaks we should make now to cleanup storybook? Seems like this component is using controls, instead of knobs, which is good. Maybe on the "Hero 5050" we can update the controls to use the color picker for `backgroundColor` and `foregroundColor`, instead of text field? "Hero Primary" already has this setup for those props.

**Comment by helenvholmes** [comment]
> This looks good. Are there any small tweaks we should make now to cleanup storybook? Seems like this component is using controls, instead of knobs, which is good. Maybe on the "Hero 5050" we can update the controls to use the color picker for `backgroundColor` and `foregroundColor`, instead of text field? "Hero Primary" already has this setup for those props.

I'm working on a second PR to clean up how Hero.Secondary works along with some of this controls work—Sharon brought up this one explicitly so I wanna get it in quick.

**Review by EdwinGuzman — APPROVED** [review]
Works well in the LCA.

**Comment by EdwinGuzman** [comment]
I just noticed this is under "Web-Based Card Creator Support". Does this mean that Sharon (et al.) want this change deployed soon as well?

**Review by nypl-wluisi — APPROVED** [review]

**Comment by helenvholmes** [comment]
> I just noticed this is under "Web-Based Card Creator Support". Does this mean that Sharon (et al.) want this change deployed soon as well?

That was certainly where she noticed the bug. I would imagine a redeployment with this work in it getting deployed along a reasonable timeline would be hoped for

**Comment by EdwinGuzman** [comment]
Yeah, that's fine, just finding that out through this PR is a bit odd to me but nbd.

**Comment by helenvholmes** [comment]
> Yeah, that's fine, just finding that out through this PR is a bit odd to me but nbd.

I hear you on that. I'm going to ask Marcus as UX lead to file a ticket for you against the Library Card app—that should have been done from the beginning anyway

**Pull request merged**
