### PR TITLE
DSD-761: Exporting the FullDateType interface

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-761](https://jira.nypl.org/browse/DSD-761)

## This PR does the following:

- Exports the `FullDateType` interface.

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr858-uppopbfberlgl9lzk6qldq3n14yzeqlm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6201828300c7e8a758560d7c

**Review by bigfishdesign13 — APPROVED** [review]
This looks good, but why does this interface need to be exported?  Also, make sure to bump up the `Latest Version` number on the story page.

**Comment by EdwinGuzman** [comment]
Crystal encountered an issue where she needed the type for retrieving data. We may need to do this more often once we start working more and more with the components.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr858-uppopbfberlgl9lzk6qldq3n14yzeqlm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6201828300c7e8a758560d7c

**Pull request merged**
