### PR TITLE
DSD-610: Updating Chakra package versions

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-610](https://jira.nypl.org/browse/DSD-610)

## This PR does the following:
- Updates Chakra packages: `@chakra-ui/react` and `@chakra-ui/system`.
- I made this update in the `Slider` component I'm working on for the `RangeSlider` component which is new, but didn't want to conflate that update with any update changes Chakra might've made. So with this PR, I reviewed all the DS stories in Storybook.
- I made minor updates but the `Accordion` story is the one that broke and froze the instance. I just had to move the `contentData` prop into the `args` in the story and that fixed it. Not completely sure what it was but something with a JSON prettier package trying to render the array.

## How has this been tested?

Storybook - all components look and function the same as before.
Ran tests - there were some new updates to a few snapshot tests which might've been minor differences by Chakra.
Ran the build - this worked fine.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
The last commit turns off a Typescript check. I can't figure out why the Chakra "descendant" package is failing but it's not our codebase. Hopefully, they make an update to this issue, unless if we're doing something wrong.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr766-mtnv4wnzqcbo3so3uzuq3wdxwqgcpoes.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6193ca23de49701172e172d3

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr766-mtnv4wnzqcbo3so3uzuq3wdxwqgcpoes.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6193ca23de49701172e172d3

**Pull request merged**
