### PR TITLE
DSD-557: Implementing the SearchBar component with the ComponentWrapper component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-557](https://jira.nypl.org/browse/DSD-557)

## This PR does the following:

- Updates the `SearchBar` component by using the `ComponentWrapper` component to implement its layout.
- Updates the `ComponentWrapper` component with `HelperErrorText`-related props to allow it to get to the invalid state.
- Adds tests for the `ComponentWrapper` component.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

- None. The main elements are still the same but the wrappers and styles have minor changes.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr829-riipvktjimgnt46wbkonb3wugrxcebyf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d5d6817499db6522ab52d5

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr829-riipvktjimgnt46wbkonb3wugrxcebyf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d5d6817499db6522ab52d5

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr829-riipvktjimgnt46wbkonb3wugrxcebyf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d5d6817499db6522ab52d5

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr829-riipvktjimgnt46wbkonb3wugrxcebyf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d5d6817499db6522ab52d5

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
Please add props for `headingText` and `descriptionText` and then pass those along to `ComponentWrapper`.  The Figma design currently do not reflect these elements, but the layout and treatment should mirror what is being done in `Slideshow` and `VideoPlayer`.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr829-riipvktjimgnt46wbkonb3wugrxcebyf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d5d6817499db6522ab52d5

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  Thanks.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr829-riipvktjimgnt46wbkonb3wugrxcebyf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d5d6817499db6522ab52d5

**Pull request merged**
