### PR TITLE
DSD-822: Chakra Style Props and HTML props

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-822](https://jira.nypl.org/browse/DSD-822)

## This PR does the following:

- Adds Chakra's "style props" functionality to all DS components. This allows the CSS property name and its shorthand as props. There is a not about how even though its available to use, it's not recommended.
- Also allows valid HTML attributes such as data-* and aria-* props to be used.
- Note that these style props affect only the wrapper element for complicated composed components. In the `SearchBar`, for example, a style prop of `padding="30px"` will target the wrapper element and not the internal `Select` element.
- This is a big change so I made it the next version `0.26.0`.
- Every component is exported by name and by the file's default export.

## How has this been tested?

Locally and Storybook.
Went through every component to make sure that style props and `data-testid` propagate correctly.

## Accessibility concerns or updates

- We are now allowing aria-* attributes for every component but we are not advertising it. Users should not have a need for them but they are allowed.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Comment by EdwinGuzman** [comment]
This is a large PR! Let me know if I can help review it.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Review by nypl-wluisi — APPROVED** [review]
@isastettler and I tested this in Scout app. Didn't notice any issues with the work done here. Did notice some issues with pagination, but those are from a prev release and bug fixes are in progress/captured on these tickets:

https://jira.nypl.org/browse/DSD-871
https://jira.nypl.org/browse/DSD-856

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Comment by EdwinGuzman** [comment]
I'm going to merge this in (after fixing merge conflicts) unless there are any issues @bigfishdesign13 @oliviawongnyc

**Comment by bigfishdesign13** [comment]
> I'm going to merge this in (after fixing merge conflicts) unless there are any issues @bigfishdesign13 @oliviawongnyc

Release the hounds!

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr901-tjwj0xdrwyjoflcngkhez3hdq2lrphcn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62325b2cfa61ec8fbfc841d7

**Pull request merged**
