### PR TITLE
DSD-502 & DSD-421: Composing the Label element with Chakra elements

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-502](https://jira.nypl.org/browse/DSD-502) and [DSD-421](https://jira.nypl.org/browse/DSD-421)

## This PR does the following:
- Uses Chakra to compose the `Label` component.
- Updates the font size to 14px.

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr705-ajvo6wo2ewshjlyjqvgftm308hapfdja.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154e0294807c0a3403e92ef

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr705-ajvo6wo2ewshjlyjqvgftm308hapfdja.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154e0294807c0a3403e92ef

**Review by bigfishdesign13 — APPROVED** [review]
This looks good.  I'm curious if the `.legend` class taht you moved will have an impact on the bug that I am seeing in `RadioGroup`.  Specifically, `RadioGroup` is showing the border.  But that matters not in this PR.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr705-ajvo6wo2ewshjlyjqvgftm308hapfdja.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154e0294807c0a3403e92ef

**Pull request merged**
