### PR TITLE
DSD-541: breakpoint CSS vars

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-541](https://jira.nypl.org/browse/DSD-541)

## This PR does the following:
- Exports the breakpoint CSS variables with the `--nypl` prefix to be in sync with the CSS variable names that Chakra exports.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr763-adxd1zugvoi6fwohlhnolqwqpzkgxwp5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618c2f3bde4970bd62dcfdc1

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr763-adxd1zugvoi6fwohlhnolqwqpzkgxwp5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618c2f3bde4970bd62dcfdc1

**Review by bigfishdesign13 — APPROVED** [review]
Terrific.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr763-adxd1zugvoi6fwohlhnolqwqpzkgxwp5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618c2f3bde4970bd62dcfdc1

**Pull request merged**
