### PR TITLE
DSD-956: cleanup console warnings

### PR DESCRIPTION
**Pull request by bigfishdesign13**
Fixes JIRA ticket [DSD-956](https://jira.nypl.org/browse/DSD-956)

## This PR does the following:

- Updates various component implementations on story and documentation pages to remove inadvertent console errors and warnings.

## How has this been tested?

- n/a

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr990-d9qrxkboissnkfejbt8ezrzoprobznjw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6274198c8a4c5796e71d3f74

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr990-d9qrxkboissnkfejbt8ezrzoprobznjw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6274198c8a4c5796e71d3f74

**Comment by EdwinGuzman** [comment]
Added an update to fix the log messages coming from the stories for the Accordion, Modal, and VideoPlayer. Other issues in the ticket are no longer issues and have been updated in other PRs.

**Comment by bigfishdesign13** [comment]
@EdwinGuzman The last updates look good.  In Chrome, I am still seeing a `DevTool failed to load source map` error related to Figma, but I am not sure that is something we can control.

**Comment by EdwinGuzman** [comment]
The `DevTool` warning is a setting in Chrome that could be turned off. They support source maps but our local Storybook instance doesn't build one. I think we could but we would have to mess with the webpack configs. I'd be more concerned about this in an application than in our Storybook instance.

**Review by EdwinGuzman — APPROVED** [review]

**Pull request merged**
