### PR TITLE
DSD-570 & DSD-527: Fixing SearchBar mobile styling and Select focus flicker

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA tickets [DSD-570](https://jira.nypl.org/browse/DSD-570) and [DSD-527](https://jira.nypl.org/browse/DSD-527)

## This PR does the following:
- Fixes the `SearchBar` mobile view by updating the border and border-radius values in the `Select` and `TextInput` components.
- Fixes the flicker that occurs when the `Select` component is focused. The right border is made transparent but when you zoom in, you notice that it's missing because the top border has a missing notch. Maybe it's not a problem but if you look at it, you can't unsee it.

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr754-timxquyxp5p4oo8jb63z5v1aomrryxzu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618579f7908ae15877533c39

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr754-timxquyxp5p4oo8jb63z5v1aomrryxzu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618579f7908ae15877533c39

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr754-timxquyxp5p4oo8jb63z5v1aomrryxzu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618579f7908ae15877533c39

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr754-timxquyxp5p4oo8jb63z5v1aomrryxzu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618579f7908ae15877533c39

**Review by bigfishdesign13 — APPROVED** [review]
Marvelous.

**Pull request merged**
