### PR TITLE
DSD-253: Storybook component categories

### PR DESCRIPTION
**Pull request by bigfishdesign13**
Fixes JIRA ticket [DSD-253](https://jira.nypl.org/browse/DSD-253)

## This PR does the following:
- groups components into categories in sidebar

## How has this been tested?

- local build of DS

## Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [x] All new and existing tests passed.

## Front End Review:

- [x] View [the example in Storybook](https://deploy-preview-615--nypl-design-system-dev.netlify.app/)

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Overall this looks great. You got the categories and grouping from a spreadsheet somewhere, right? Maybe an explanation in the description and maybe somewhere in the readme would help to explain the context and how the categorization came about.

Is it possible to have the subcategories, such as `Basic Element`, `Content Display`, etc, opened by default? It's harder now to know where a component lives. I tried looking for `Accordion` and, because it's no longer alphabetical, I had a hard time looking or knowing where it would be located.

**Comment by bigfishdesign13** [comment]
> Overall this looks great. You got the categories and grouping from a spreadsheet somewhere, right? Maybe an explanation in the description and maybe somewhere in the readme would help to explain the context and how the categorization came about.

Yes, the categories are listed under one of the tabs in the component matrix dovument.  This is something that Kathy and I have neen discussing for a while.  I will add a brief explanation on the `README` and on the Storybookj `Introduction` page.

> Is it possible to have the subcategories, such as `Basic Element`, `Content Display`, etc, opened by default? It's harder now to know where a component lives. I tried looking for `Accordion` and, because it's no longer alphabetical, I had a hard time looking or knowing where it would be located.

As I mentioned, this is something that I already started to look into.  No luck yet, but I will spend some more time on this.

**Review by EdwinGuzman — APPROVED** [review]
For context, these categories are in the component audit matrix spreadsheet but is there another defining source that says "these are the categories moving forward"? Or is the matrix spreadsheet the main source?

**Comment by bigfishdesign13** [comment]
> For context, these categories are in the component audit matrix spreadsheet but is there another defining source that says "these are the categories moving forward"? Or is the matrix spreadsheet the main source?

@EdwinGuzman At the moment, the matrix file is the only place where the categories are listed.  Now that we have settled on these groupings, I will create an official doc listing and explaining.  The Figma Main file will also be updated to reflect these new categories.  And when time allows, I would also like to update Metronome to reflect these cagtegories.

**Pull request merged**
