### PR TITLE
DSD-923 - Select remove unnecessary spacing

### PR DESCRIPTION
**Pull request by knezmilos**
Fixes JIRA ticket DSD-923

## This PR does the following:

- Removes unnecessary margin-bottom spacing on the Select component

## How has this been tested?

Storybook

## Accessibility concerns or updates

N/A

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr983-7sy6mwbf2ijczix9mfud0kwtogmwexiz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626dec068a4c5796e73ff70c

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
Make sure to update the CHANGELOG and to update the Latest Version number on the `Select` story page.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr983-7sy6mwbf2ijczix9mfud0kwtogmwexiz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626dec068a4c5796e73ff70c

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  Just make sure to update the `Latest Version` number on the story page before you merge.

**Review by EdwinGuzman — APPROVED** [review]

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr983-7sy6mwbf2ijczix9mfud0kwtogmwexiz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626dec068a4c5796e73ff70c

**Pull request merged**
