### PR TITLE
DSD-425: Updating the font size of the Button component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-425](https://jira.nypl.org/browse/DSD-425)

## This PR does the following:
- Updates the font size to "-1" or 14px.
- The `ButtonGroup` was always re-exported from Chakra but this makes it clearer where it's coming from.
- Updating the Storybook documentation with updated variants.

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr745-4noamstapi6aviyydezylzr2osdmrx0q.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617c40b76d8bf7b3ff89334f

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
The font re-sizing looks good, but that is now impacting `SearchBar`.  The button is now too short.  I think the best way to address this is to adjust the `lineHeight` for the button used in `SearchBar`.  It seems like 1.75 worked well.  Also, `marginTop` on the `Icon` will need to be increased.  Unfortunately, there is no canned value that will work and you'll need to hardcode `6px`.

**Comment by EdwinGuzman** [comment]
I pushed an update but didn't need to update the `marginTop` rule. Did you mean to add it to the `Icon` in the `SearchBar` button?

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr745-4noamstapi6aviyydezylzr2osdmrx0q.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617c40b76d8bf7b3ff89334f

**Review by bigfishdesign13 — APPROVED** [review]
Yes, the `padding-top` recommendation was for the `Icon` within the `Button` within `SearchBar`.  But don't worry about it.  This update looks good as is.

**Pull request merged**
