### PR TITLE
DSD-667: Select - allow init empty value prop for controlled components

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-667](https://jira.nypl.org/browse/DSD-667)

## This PR does the following:

- Allows for an initial empty `value` prop for controlled `Select` components.
- Adds updated documentation on how to pass in and extract values with both controlled and uncontrolled types.
- Passing a `ref` prop for the uncontrolled state still works.
- Adds `placeholder` prop for the `Select` component.
- Check the `Select` story at the end for examples with logged messages to the console for both controlled and uncontrolled types.

## How has this been tested?

Only through Storybook but should be tested in other test apps. Please also review the `SearchBar` component as it also uses the `Select` component. Similar to the `Select`, open up the console and check for logged messages when submitting the form.

## Accessibility concerns or updates

- None, aria attributes are still there.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr814-ejy45fxlpzbrvs0ckpgfuym9lps8iwyt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c0c6e25f46ed13d8460ad4

**Review by nypl-wluisi — APPROVED** [review]
@EdwinGuzman Tested this in Scout, controlled selects are working properly again!

**Comment by EdwinGuzman** [comment]
I wonder if "properly" is with or without the empty `value` prop. We'll have to do more investigation on this in case there are other docs (besides the React docs) that say otherwise.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr814-ejy45fxlpzbrvs0ckpgfuym9lps8iwyt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c0c6e25f46ed13d8460ad4

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr814-ejy45fxlpzbrvs0ckpgfuym9lps8iwyt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c0c6e25f46ed13d8460ad4

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr814-ejy45fxlpzbrvs0ckpgfuym9lps8iwyt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c0c6e25f46ed13d8460ad4

**Pull request merged**
