### PR TITLE
DSD-869: StructuredContent HTML element styling

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-869](https://jira.nypl.org/browse/DSD-869)

## This PR does the following:

- Adds native HTML element styles inside the `StructuredContent` component. These styles are the same as what the related DS component has for its styles.
- These styles are scoped to the `StructuredContent` component. So if there is a native `table` element that is not the DS `Table` component and it is not inside the `StructuredContent` component, then it _won't_ pick up the right styles. This also follows for ul, ol, dl, dt, dd, div, section, h* headings, table, th, and td.

@nypl-wluisi  can you test this and remove what you have in this file: https://github.com/NYPL/dxp-react-search/blob/development/src/components/shared/TextFormatted/TextFormatted.tsx
Note that some values have been updated to match what the value is in the DS component.

## How has this been tested?

Storybook, there is an updated example that uses native HTML elements.
This was also tested by linking to the DS test app. Here is the relevant branch: https://github.com/NYPL/nypl-ds-test-app/tree/DSD-869/structuredcontent-styling

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr949-l2tc6dsmflt0cmqzmahicac2v4iv3zxp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255ef167dc9604ba3fb4141

**Review by bigfishdesign13 — APPROVED** [review]
This looks good to me.  The styles for the noted tags are being rendered properly when they come in an plain HTML tags.  I will approve, but wait for @nypl-wluisi to take it for a spin in the Scout app before merging.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr949-l2tc6dsmflt0cmqzmahicac2v4iv3zxp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255ef167dc9604ba3fb4141

**Review by nypl-wluisi — APPROVED** [review]

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr949-l2tc6dsmflt0cmqzmahicac2v4iv3zxp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255ef167dc9604ba3fb4141

**Pull request merged**
