### PR TITLE
DSD-613: Exporting missing components and variables

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-613](https://jira.nypl.org/browse/DSD-613)

## This PR does the following:
- Exports components and variables that were missed the first time around.

## How has this been tested?

Bug caught in prod (specifically the `ColorVariants` for the `Breadcrumbs` component).

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr768-7mujhryiizt9mkzhhn0ow5bu3yvtzwrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619573b2e3686523f3406ef0

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr768-7mujhryiizt9mkzhhn0ow5bu3yvtzwrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619573b2e3686523f3406ef0

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr768-7mujhryiizt9mkzhhn0ow5bu3yvtzwrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619573b2e3686523f3406ef0

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr768-7mujhryiizt9mkzhhn0ow5bu3yvtzwrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619573b2e3686523f3406ef0

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  Thanks for the cleanup.

**Pull request merged**
