### PR TITLE
DSD-616: Updating some packages to try to keep up-to-date

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-616](https://jira.nypl.org/browse/DSD-616)

## This PR does the following:
- Updates some Storybook packages and webpack loaders, and removes packages that are not being used.
- This PR doesn't really fix some security issues raised by Github's Dependabot but we'll get there slowly...

## How has this been tested?

Deleted `node_modules` and `package-lock.json`, ran `npm i`, `npm run storybook`, and `npm test`.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr779-6fcseoqinp03pnexsjbsbhbcxgh6r4fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d1180de49703eece72c87

**Review by bigfishdesign13 — APPROVED** [review]
Staying current.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr779-6fcseoqinp03pnexsjbsbhbcxgh6r4fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d1180de49703eece72c87

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 I'm going to merge this to `development` and test tugboat again.

**Pull request merged**
