### PR TITLE
DSD-525: Chakra SkeletonLoader

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-525](https://jira.nypl.org/browse/DSD-525)

## This PR does the following:
- Composes the DS `SkeletonLoader` component with Chakra's `Skeleton` component.

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr748-hysja22ylzw6pzwtiqocppwatylcdrxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618046c635001899157bc11c

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr748-hysja22ylzw6pzwtiqocppwatylcdrxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618046c635001899157bc11c

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr748-hysja22ylzw6pzwtiqocppwatylcdrxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618046c635001899157bc11c

**Comment by bigfishdesign13** [comment]
There are some styling issues with padding and image sizing.  I will take a closer look after I review the other PRs.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr748-hysja22ylzw6pzwtiqocppwatylcdrxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618046c635001899157bc11c

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr748-hysja22ylzw6pzwtiqocppwatylcdrxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618046c635001899157bc11c

**Comment by EdwinGuzman** [comment]
Last update looks good.

**Review by bigfishdesign13 — APPROVED** [review]
Tag-team approval.

**Pull request merged**
