### PR TITLE
DSD-942: Allows JSX elements to be rendered in the Table component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-942](https://jira.nypl.org/browse/DSD-942)

## This PR does the following:

- Allows JSX elements to be rendered in the `Table` component.

## How has this been tested?

Storybook .

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr981-c7fjb6ci0o1nbkkrrllemsd4p7tsva9f.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626af3492e91387b17c7d334

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr981-c7fjb6ci0o1nbkkrrllemsd4p7tsva9f.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626af3492e91387b17c7d334

**Review by nypl-wluisi — APPROVED** [review]
Looks good

**Review by bigfishdesign13 — APPROVED** [review]
Very nice.  I love the pictures in the example table.

**Pull request merged**
