### PR TITLE
DSD-958: URL link cleanup

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-958](https://jira.nypl.org/browse/DSD-958)

## This PR does the following:

- This PR is meant to be merged right before the v1 release.
- Cleans up the production URLs to point to the correct location.
- The base URL doesn't actually work yet. All the links are updated to `https://nypl.github.io/nypl-design-system/reservoir/v1` but the current URL is `https://nypl.github.io/nypl-design-system/reservoir/v0`.

## How has this been tested?

Locally.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr989-vc0h35kglc6mefnwt81offy6dndqd0qg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62741894ef17c6f5691090a2

**Review by nypl-wluisi — APPROVED** [review]

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr989-vc0h35kglc6mefnwt81offy6dndqd0qg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62741894ef17c6f5691090a2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr989-vc0h35kglc6mefnwt81offy6dndqd0qg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62741894ef17c6f5691090a2

**Pull request merged**
