### PR TITLE
DSD-910: Fixing bad storybook args which caused Pagination log message

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-910](https://jira.nypl.org/browse/DSD-910)

## This PR does the following:

- Explicitly passed `undefined` for function props in the `Pagination` component so the console warning does not get logged.

## How has this been tested?

Storybook

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Review by bigfishdesign13 — COMMENTED** [review]
This change will resolve what we are seeing in Storybook, but what about general usage in a consuming app?  Should a consuming app be expected to add a value of `undefined` for a prop that is not being used?

**Comment by EdwinGuzman** [comment]
No, this is only an issue with Storybook. The warning messages don't come up in the Test app. It's also not a problem in the last example in the Storybook doc page with the "Go to Page 1" button. I think it's Storybook's `Story` that confuses the component and the props it receives.

**Review by bigfishdesign13 — APPROVED** [review]
Works for me!

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr944-fkjl2miovbqdd3wammyi2dnstxowlqfo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6254342ed9027707d317bcef

**Pull request merged**
