### PR TITLE
DSD-500: Carousel hook

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-500](https://jira.nypl.org/browse/DSD-500)

## This PR does the following:
- This adds a `useCarouselStyles` custom hook that returns two functions `nextSlide` and `prevSlide` used for sliding programmatically, and a `carouselStyle` JS object used for styling the carousel wrapper. All three must be used together to be able to "slide" within a container wrapper for slide elements.
- This is implemented in the `Tabs` component for the mobile view.
- This wraps around the container, so if you reach the last element and invoke the `nextSlide` function, it'll go to the first slide. Likewise, if you are on the first slide and invoke the `prevSlide` function, it'll go to the last slide.
- @nypl-wluisi I think this should work well for the `Slideshow` component but if it needs adjuments, that's fine. Let me know or you can modify it once the `Slideshow` work begins. Either way, this should help start the implementation for that component.
- @bigfishdesign13 I need some help with the focus styles for the buttons. I can't get the left or right focus outline to display correctly but maybe it's not a big deal:

Screen Shot 2021-09-28 at 10 47 27 AM

## How has this been tested?

Through Storybook's responsive viewport feature.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
Ready for review @bigfishdesign13  @nypl-wluisi

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Review by bigfishdesign13 — APPROVED** [review]
This is working well, but there are some issues with the scroll positioning.  I will approve this, but we need to come back to the scroll issues.

**Comment by bigfishdesign13** [comment]
@nypl-wluisi Can you give this a review before it is merged?

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Comment by EdwinGuzman** [comment]
@nypl-wluisi Can you review this when you get a chance?

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr699-dkzycddnjdj3vkwnvibrvhb5jdo7fece.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615347247207f285e32cb7e2

**Review by nypl-wluisi — APPROVED** [review]
Looks good to me. Can give it a closer look when I work on slideshow

**Pull request merged**
