### PR TITLE
DSD-868: Checkbox JSX labels and full-width CheckboxGroup

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-868](https://jira.nypl.org/browse/DSD-868)

## This PR does the following:

- Adds the `isFullWidth` prop to the `CheckboxGroup` component. This sets the checkbox's wrapper element to be full width for labels that need to span its container.
- Updates the `Checkbox`'s `labelText` prop to accept strings and JSX Elements.

This came up because @gonuguntla  needs this layout for MLN.

Here's an updated example in the [`Form` page](https://pr905-j5crffwq6exmwezq9kga9eqx2cnpgvoh.tugboat.qa/?path=/story/components-form-elements-form--form-with-controls):

Screen Shot 2022-03-18 at 4 35 22 PM

## How has this been tested?

Storybook

## Accessibility concerns or updates

- For the `Checkbox` component, when we want to hide the label through the `showLabel` prop, the `labelText` is used as the aria-label. If the passed value to `labelText` is a JSX element and the label is hidden, a warning is thrown. This is not allowed because we can't convert the JSX to a string to use in the `aria-label` attribute.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [x] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr905-j5crffwq6exmwezq9kga9eqx2cnpgvoh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6234f095c49d661fdc5946da

**Review by bigfishdesign13 — CHANGES_REQUESTED** [review]
This looks good, but I am curious how this will be digested by a screenreader.  The testing for `CheckboxGroup` now has a snapshot test for this config, but the `a11y` does not target this.  Can you include `a11y` testing on an exmple using this new functionality?

Also, this same functionality should be applied to `RadioGroup`.

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 updated, but GA is down so I'll re-run them when it's working again.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr905-j5crffwq6exmwezq9kga9eqx2cnpgvoh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6234f095c49d661fdc5946da

**Review by bigfishdesign13 — APPROVED** [review]
Nice.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr905-j5crffwq6exmwezq9kga9eqx2cnpgvoh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6234f095c49d661fdc5946da

**Pull request merged**
