### PR TITLE
Prep for Release v3.1.1

### PR DESCRIPTION
**Pull request by EdwinGuzman**
## This PR does the following:

- Prep for release 3.1.1.

### CODE REVIEW

**Comment by bigfishdesign13** [comment]
@EdwinGuzman The `Latest Version` also needs to be updated on the story pages.

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 updated

**Review by bigfishdesign13 — APPROVED** [review]
The component changelog for `FeaturedContent` was updated, but there is nothing mentioned in the app CHANGELOG.  Also, the `Latest Version` on the `FeaturedContent` story page needs to be updated.

**Comment by EdwinGuzman** [comment]
Gotcha, updated and will merge soon.

**Pull request merged**
