### PR TITLE
DSD-933: Fixing controlling the Select component in the SearchBar component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-933](https://jira.nypl.org/browse/DSD-933)

## This PR does the following:

- Exposes the `value` key in the `selectProps` for the `SearchBar` component. This sets the `Select` component as a "controlled" component  but `value` AND `onChange` _must_ be passed.
- There's an example in Storybook handling the start in the function that renders the `SearchBar`.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr964-ekwofkbpfhlqwgnveasiuqrpqrajrnpo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625f1a358a4c5796e74753d8

**Review by jackiequach — APPROVED** [review]
Looks good! I tested DRB locally and on Tugboat.

**Review by bigfishdesign13 — APPROVED** [review]
The code looks good and I am relying on Jackie’s functional testing as being valid.  All good!

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr964-ekwofkbpfhlqwgnveasiuqrpqrajrnpo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625f1a358a4c5796e74753d8

**Pull request merged**
