### PR TITLE
SFR-712 search bar

### PR DESCRIPTION
**Pull request by hokei**
[Project Reno Jira Ticket](http://jira.nypl.org/browse/RENO-XXX)

[ResearchNow Jira Ticket](http://jira.nypl.org/browse/SFR-712)

## **This PR does the following:**
- Added the Search Bar and the Search version of textInput and Button.

### Front End Review:
- [ ] View [the example in Storybook](https://reno-XXX-nypl.pantheonsite.io/themes/custom/nypl_emulsify/pattern-lab/public)
- [ ] Check against the [Metronome documentation](http://themetronome.co/components/xxx/?fresh=true)

### CODE REVIEW

**Comment by hokei** [comment]
@helenvholmes : If you could take a look at the CSS for this?  I'm not sure that it's the right thing to be using `form-item__textfield` ... In addition, I'm not sure where to look for the default width of the searchbar?  Thanks!  

This definitely still needs some work, eg: unit tests, placeholdering the placeholder text, etc.  I will be working on this in parallel

**Comment by helenvholmes** [comment]
@hokei Hey Crystal, I'm not seeing any CSS with class `.form-item__textfield `—is it possible you have unpushed changes?

**Comment by hokei** [comment]
@helenvholmes It's a class I was trying to re-use: https://github.com/NYPL/nypl-design-system/blob/development/src/styles/01-atoms/forms/textfields/_textfields.scss#L22

**Review by helenvholmes — APPROVED** [review]
👍🏼 LGTM!

**Comment by hokei** [comment]
Screen Shot 2019-12-04 at 11 14 05 AM

Just adding this here to keep track of it.  This is on FF - things look good in chrome!

**Pull request merged**
