### PR TITLE
DSD-483: Adding ui/error/secondary color and updating names

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-483](https://jira.nypl.org/browse/DSD-483)

## This PR does the following:
- Adds the `ui.error.secondary` color.
- Updates color names to be consistent with NYPL Figma -- on both the Chakra theme and in the existing SCSS files.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr690-s8qsvqhkm7ncq49qj1gex7xnks7u1kox.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614cd29dd7000a5ba649ab26

**Review by bigfishdesign13 — COMMENTED** [review]
This was more of an undertaking than I anticipated and overall it looks good.  However, there are a few more files that need to be updated.  The following SCSS files all use the `--ui-error` CSS var and those references now need to be flipped to `--ui-error-primary`.

- _HelperErrorText.scss
- _Input.scss
- _Select.scss
- _TextInput.scss

**Comment by EdwinGuzman** [comment]
Missed those, thanks. Updated.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr690-s8qsvqhkm7ncq49qj1gex7xnks7u1kox.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614cd29dd7000a5ba649ab26

**Review by bigfishdesign13 — APPROVED** [review]
The changes look good!

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr690-s8qsvqhkm7ncq49qj1gex7xnks7u1kox.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614cd29dd7000a5ba649ab26

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr690-s8qsvqhkm7ncq49qj1gex7xnks7u1kox.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614cd29dd7000a5ba649ab26

**Pull request merged**
