### PR TITLE
DSD-806: font styles for input components

### PR DESCRIPTION
**Pull request by bigfishdesign13**
Fixes JIRA ticket xxx

## This PR does the following:

- Updates font size to "12px" and top margin to "4px" for `HelperErrorText` component.
- Updates font size to "14px" for `TextInput` component.

## How has this been tested?

- n/a

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr877-jwpaxljzl9dvvlpmlojuwpgbtlmrqisf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6214134ddf1c1f9d5e680d6c

**Review by EdwinGuzman — COMMENTED** [review]
Looks good but some invalid text look very small next to the helper test:
Screen Shot 2022-02-22 at 9 33 23 AM

In the `SearchBar` with a `Select`, the helper text has more margin than the `SearchBar` without the `Select`. This doesn't seem intentional.

And just curious, why the font change and margin?

**Comment by bigfishdesign13** [comment]
> Looks good but some invalid text look very small next to the helper test: Screen Shot 2022-02-22 at 9 33 23 AM
> 
> In the `SearchBar` with a `Select`, the helper text has more margin than the `SearchBar` without the `Select`. This doesn't seem intentional.
> 
> And just curious, why the font change and margin?

@EdwinGuzman,

The font size in the React components was wrong when comparing to the Figma designs.  Figma has it as 12px, but the React component was set to 14px.  For the spacing, 4px feels better overall.  There are some cases where it will need top be cleaned up.  And you just found one in `DatePicker`.  Let me see what I can do about that one now.

The spacing issues in SearchBar are related to the button component.  When the `showSelect` is true, the button has a bottom margin of 9px.  But that is removed when `showSelect` is false.  I will add that to the issue tracker.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr877-jwpaxljzl9dvvlpmlojuwpgbtlmrqisf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6214134ddf1c1f9d5e680d6c

**Review by EdwinGuzman — APPROVED** [review]
Looks good. I noticed that the update you made for the `DatePicker` is similar to how every component that implements a `HelperErrorText` component implements -- they all have a `Box` component with a "helper" CSS object. Maybe we should move that base style over to the `HelperErrorText` component, eventually.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr877-jwpaxljzl9dvvlpmlojuwpgbtlmrqisf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6214134ddf1c1f9d5e680d6c

**Pull request merged**
