### PR TITLE
DSD-104: Using gulp-concat for resources.scss

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-104](https://jira.nypl.org/browse/DSD-104)

## This PR does the following:

- Replaces the `gulp-scss-combine` package with `gulp-concat` to combine all the necessary scss files with variables that consuming apps need. This is based on `src/resources.scss` so we can eventually remove it and just rely on the gulp file.
- The `gulp-scss-combine` package has some security issues so, while this is not the best scss process, it removes potential issues.
- The original ticket says to use a webpack task but this was before we moved to `tsdx`. We can hook into the tsdx rollup config but can't create another task for _just_ combining scss. We can try other builders like parcel but gulp is lightweight enough and this task is lightweight enough that we shouldn't over-engineer this.
- We should, eventually, figure out if we need the scss mixins under the `/space/` directory or if any consuming apps need it.

## How has this been tested?

Running `npm run build` and reviewing the `/dist/resources.scss` file.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr870-rlandwt6gt4ac2ygtg761zfvc6eymjti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/620ad45adae2dd15a5849b21

**Review by bigfishdesign13 — APPROVED** [review]
Sure thing.

**Comment by bigfishdesign13** [comment]
@EdwinGuzman Let’s use Slack to get some feedback from FEDs about whether any of the SCSS mixins are being used in consuming app.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr870-rlandwt6gt4ac2ygtg761zfvc6eymjti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/620ad45adae2dd15a5849b21

**Pull request merged**
