### PR TITLE
DSD-691: Link custom anchor styles bug fix

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-691](https://jira.nypl.org/browse/DSD-691)

## This PR does the following:

- Fixes the styles of custom anchor elements in the `Link` component when they are passed as a child prop.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr833-npj5pidbb1vhy17wug0m1l9lo3wjpre1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d74ff65f46ed13d8e1906f

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr833-npj5pidbb1vhy17wug0m1l9lo3wjpre1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d74ff65f46ed13d8e1906f

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr833-npj5pidbb1vhy17wug0m1l9lo3wjpre1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d74ff65f46ed13d8e1906f

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr833-npj5pidbb1vhy17wug0m1l9lo3wjpre1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d74ff65f46ed13d8e1906f

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr833-npj5pidbb1vhy17wug0m1l9lo3wjpre1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61d74ff65f46ed13d8e1906f

**Pull request merged**
