### PR TITLE
DSD-622: Using nvm to set the Node version

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-622](https://jira.nypl.org/browse/DSD-622)

## This PR does the following:
- Adds an `.nvmrc` file to set the node version to 12.22.x through nvm. 
- Specifies to use Node version >10 and <=12 in `package.json`.

## How has this been tested?

I am using Node version 12.22.1 and not nvm. If you're using it, it'd be helpful to run `nvm use`, install packages, run the build, and then run Storybook to make sure it's all working. The LTS for Node 12 is 12.22.7 but setting it to `12.22` will pick up the latest patch version.

This sets the recommended node version but doesn't fix the underlying issue which _I think_ might be the `node-sass` version we are using. Until we can remove it or update it, this problem may keep coming up on Node versions 14 and 16 (which I've been told have issues).

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr790-lyvvw7hrercavxe6f1bjwfohlallst7l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61aa75b70048b872947bac4e

**Review by bigfishdesign13 — COMMENTED** [review]
This looks good to me. @hokei and @nypl-wluisi, can you also put your final stamps of approval on this?

**Comment by hokei** [comment]
I generally don't have issues developing on design system or storybook on node 16.  I intermittently run into `node-sass` issues but `npm rebuild node-sass` fixes it for me.  

I run into`module_not_found` issues on DRB using node 16, but I don't have similar problem running the test app
Screen Shot 2021-12-07 at 3 46 59 PM
Screen Shot 2021-12-07 at 3 47 23 PM

**Comment by EdwinGuzman** [comment]
@hokei , that's good to know you have no issues with node 16. I know @wluisi ran into issues and suggested we try nvm to see if that works.

**Comment by bigfishdesign13** [comment]
@nypl-wluisi Can you give this a review?  I would like to include the PR in tomorrow's release.  Thanks.

**Review by nypl-wluisi — APPROVED** [review]
Looks good

**Review by bigfishdesign13 — APPROVED** [review]
Everyone approves!

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr790-lyvvw7hrercavxe6f1bjwfohlallst7l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61aa75b70048b872947bac4e

**Pull request merged**
