### PR TITLE
DSD-508: Chakra Pagination

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-508](https://jira.nypl.org/browse/DSD-508)

## This PR does the following:
- Note: this is based on PR #726 
- Updates the `Pagination` component to use Chakra components and styling.
- Updated the `Pagination` component to more closely resemble what is in Figma.
- Updates the `List` and `Link` components with minor updates in order to render the `Pagination` correctly.
- Does not change any existing behavior but just its internal implementation.
- This component was very complex before and took a while to refactor... I wrote plenty of comments but please take a look and make sure it makes sense and is easy to pick up.
- While working on this, I was thinking if maybe we _should_ keep track of the current page ourselves. We chose not to before because we decided not to export components that use state. This has changed so perhaps now is the time to store the current page in the component and expose it to the parent wrapper component that renders it. In this case, maybe it would be better to have `initialPage` instead of `currentPage`, and also pass a callback function to retrieve that value.
  - I'm not sure how anyone is actually using this component but once we get feedback, _then_ we should make any behavior updates.
  - We should create a ticket for this next iteration.

## Accessibility

Based the accessibility attributes on these sources:

- https://www.a11ymatters.com/pattern/pagination/
- https://designsystem.digital.gov/components/pagination/
- https://a11y-style-guide.com/style-guide/section-navigation.html

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr731-bjqv0avrbhr3qxkwac89pj3wfm6wfhci.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617024ff1ff56a68e9ec5a57

**Review by bigfishdesign13 — COMMENTED** [review]
This looks good and functions well, but I would like to talk about the `page refresh` vs. `no page refresh` functionality.

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 this now keeps the current page in state inside of the component and returns the selected current page through the `getPageHref` or `onPageChange` functions.

**Review by bigfishdesign13 — APPROVED** [review]
This looks good and I like the changes.  I will approve this PR, but I think it would also be good to get an approval from @hokei or @nypl-wluisi.

**Comment by EdwinGuzman** [comment]
@hokei @nypl-wluisi nudge.

**Review by nypl-wluisi — APPROVED** [review]
Code looks good.

**Pull request merged**
