### PR TITLE
Updating storybook dependencies

### PR DESCRIPTION
**Pull request by hokei**
Fixes #xxx

## **This PR does the following:**
- Upgrades the storybook addons so that they're not causing security errors

### Front End Review:
- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by kaplanmichael** [comment]
@hokei are the failing checks above related to the github action issues we've been facing?

**Comment by hokei** [comment]
I'm getting test failures locally.  I've had issues with my local environment for a bit though so if you can pull and build properly feel free to push to this branch and we can get on with having it merge.

**Comment by hokei** [comment]
@kaplanmichael should all work now.

**Review by kaplanmichael — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
