### PR TITLE
DSd-1401: Updating react-datepicker package

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-1401](https://jira.nypl.org/browse/DSD-1401)

## This PR does the following:

- Updates the `react-datepicker` npm package. The previous version was logging a warning which is annoying to see in the build process:
Screen Shot 2023-06-29 at 4 42 16 PM

- This has been fixed in the latest version.
- There are no functional or visual changes.

## How has this been tested?

Locally.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 can we get Clare to review this once approved but before it gets merged in?

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  The component appears to be working as expected.

**Comment by bigfishdesign13** [comment]
> @bigfishdesign13 can we get Clare to review this once approved but before it gets merged in?

@EdwinGuzman Yes, I just sent a link to Clare and asked her to take a look from an a11y point of view.

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 I don't think she ever did an a11y audit on this component to begin with, so while the review is great, we don't have a baseline to compare it to. I noticed a slight difference in how a label is rendered so that's why I asked for the a11y review.

**Comment by bigfishdesign13** [comment]
@EdwinGuzman Actually, Clare completed the a11y review of all form components at the end of last week.  While we haven't made any changes yet based on that review, we can at least see if any additional issues were introduced with this latest update for `DatePicker`.

**Comment by EdwinGuzman** [comment]
Great, is the audit part of this work https://jira.nypl.org/browse/DSD-1250?

**Pull request merged**
