### PR TITLE
DSD-405: DatePicker functionality in consuming apps

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-405](https://jira.nypl.org/browse/DSD-405)

## This PR does the following:
- Allows the `DatePicker` component to function as both uncontrolled and controlled React form components.
- Added documentation on how to use the uncontrolled and controlled versions.
- An `onChange` function can be passed as a prop for controlled components.
- For uncontrolled components, `nameFrom` and `ref` should be passed for single date fields. For a date range, additional `nameTo` and `refTo` must be passed.
- This uses `forwardRef` for the initial `ref` prop but then an actual prop for the `refTo`. Internally, the "React DatePicker" plugin works with refs so there is some minor manipulation to get it to work.
- Updates the shape of the internal state from separate `startDate` and `endDate` values to a single object with `startDate` and `endDate` keys.
- Adds warnings if props aren't used correctly.

## How has this been tested?

Locally as well as through `npm link` in the Location Finder app and the Library Card app.

@hokei @nypl-wluisi if possible, can you test in your respective apps?

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
@hokei @wluisi @bigfishdesign13 
❗ 👀  PR review ping  👀 ❗

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr639-sbowscxm9lzqbcfmwm9z8tjltoz3xjio.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611d6955378c5f131c83a331

**Review by hokei — APPROVED** [review]
Pulled into DRB and it looks like it's working

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr639-sbowscxm9lzqbcfmwm9z8tjltoz3xjio.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611d6955378c5f131c83a331

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr639-sbowscxm9lzqbcfmwm9z8tjltoz3xjio.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611d6955378c5f131c83a331

**Comment by EdwinGuzman** [comment]
This has been updated. @wluisi let me know if you can test this in your app, otherwise I'll merge and ask QA to review.

**Review by nypl-wluisi — APPROVED** [review]
Looks good

**Pull request merged**
