### PR TITLE
Icons for Location Finder + Web-Based Card Creator

### LINKED ISSUE #271: Add New Icons
### Component in question:
- `Icon`

### Description of issue:
Location Finder needs:
- [x] Fully accessible icon
- [x] Partially accessible icon
- [x] Clock icon (???)
- [x] Checkmark icon
- [x] Close icon
- [x] Download icon

### PR DESCRIPTION
**Pull request by helenvholmes**
Issue number: #271

## **This PR does the following:**
- Adds new icons for Location Finder
- Updates the download icon to Google Material Design's icon (old icon was fuzzy at small sizes)
- Adds stories for `Icon`

### Front End Review:
- [ ] View [Icon in Storybook](http://localhost:9001/?path=/story/icon--icons)

### CODE REVIEW

**Review by EdwinGuzman — APPROVED** [review]
Looks good and the check icon is not available for the Button component (which was my request from [library card app 49](https://github.com/NYPL/nypl-library-card-app/pull/49) ).

**Comment by helenvholmes** [comment]
@EdwinGuzman Hey Edwin, what do you mean it's not available for the Button component? I'm a little confused—I'm seeing if [here](http://localhost:9001/?path=/story/button--button) in the knobs, or did you need something else?

**Comment by EdwinGuzman** [comment]
Sorry, typo! I meant "now"! All is good.

**Comment by helenvholmes** [comment]
@EdwinGuzman oh phew 😅

**Pull request merged**
