### PR TITLE
DSD-566: Card element spacing

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-566](https://jira.nypl.org/browse/DSD-566)

## This PR does the following:
- Updates the spacing of internal elements in the `Card` component.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr759-9t2oup8nfimqvrknehsf5ienknfhi0dw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618a94fee368652a1738bfcc

**Review by bigfishdesign13 — APPROVED** [review]
Marvelous.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr759-9t2oup8nfimqvrknehsf5ienknfhi0dw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618a94fee368652a1738bfcc

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr759-9t2oup8nfimqvrknehsf5ienknfhi0dw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618a94fee368652a1738bfcc

**Pull request merged**
