### PR TITLE
DSD-928: Removing the additionalStyles prop and using style props instead

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-928](https://jira.nypl.org/browse/DSD-928)

## This PR does the following:

- Removes the `additionalStyles` attributes from the `Breadcrumbs`, `Button`, `Heading`, `HelperErrorText`, `Icon`, `Link`, `List`, `Logo`, `Select`, `TextInput`, and `Toggle` components.
- Updates how styles are passed down to internal components in `Card`, `Checkbox`, `CheckboxGroup`, `ComponentWrapper`, `DatePicker`, `Hero`, `Notification`, `Pagination`, `Radio`, `RadioGroup`, `SearchBar`, and `Slider`. This is based on removing the `additionalStyles` prop and passing down styles to the `__css` prop.
- Updates how the `id` is passed in the `DatePicker`'s custom `TextInput` component.

## How has this been tested?

Locally and Storybook. All components were reviewed but they should be re-reviewed.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr973-1pceixbmhxp00fwthskd8wiubickhrfw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266e8448a3b7b49de2ce8c0

**Review by bigfishdesign13 — APPROVED** [review]
I initially had some question, but I was able to answer my own questions.  This looks good.  I pulled the branch into Turbine and my spot-checks looked good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr973-1pceixbmhxp00fwthskd8wiubickhrfw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266e8448a3b7b49de2ce8c0

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr973-1pceixbmhxp00fwthskd8wiubickhrfw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266e8448a3b7b49de2ce8c0

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr973-1pceixbmhxp00fwthskd8wiubickhrfw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266e8448a3b7b49de2ce8c0

**Pull request merged**
