### PR TITLE
DSD-798: Updating list styles for inline

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-798](https://jira.nypl.org/browse/DSD-798)

## This PR does the following:

- Removes the margin for the first list item in a `List` when `inline` is true.
- Adds a bit more padding between list items but still keeps the flex layout. This may need a larger update to get this right or maybe not use this anymore because you're right, it'll need more updates if we want this right.
 
## How has this been tested?

Storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr883-oh9qxjhneyj3mklminnuvhwp5ehcycti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/621ffdad01c6d20b85e5d8a2

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr883-oh9qxjhneyj3mklminnuvhwp5ehcycti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/621ffdad01c6d20b85e5d8a2

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  And I was wrong about the overlap of `inline` and `noStyle`.  The bullets are still there when `inline` is true.  You do need to explicitly use `noStyle` to remove them.  That said, let’s keep thinking about `inline` and its use.

**Comment by EdwinGuzman** [comment]
@bigfishdesign13  I updated the prop type for the "definition" to allow JSX.

**Pull request merged**
