### PR TITLE
DSD-699: Updating the spacing for the Toggle component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-699](https://jira.nypl.org/browse/DSD-699)

## This PR does the following:

- Updates Chakra's `Switch` component height and width CSS variables to better style the DS `Toggle` button.
Let me know if this is what you were thinking or if it's close to Figma.

## How has this been tested?

Storybook

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr914-wo2vrcjxqd6ongi1g6hl9e7w0vkztr1u.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/623cdd84957a037a163cb3fe

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr914-wo2vrcjxqd6ongi1g6hl9e7w0vkztr1u.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/623cdd84957a037a163cb3fe

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr914-wo2vrcjxqd6ongi1g6hl9e7w0vkztr1u.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/623cdd84957a037a163cb3fe

**Pull request merged**
