### PR TITLE
DSD-1280: Fixes styling for clear button, updates snapshots

### PR DESCRIPTION
**Pull request by oliviawongnyc**
Fixes JIRA ticket [DSD-1280](https://jira.nypl.org/browse/DSD-1280).

** This is a new PR for the same clear button work because my old PR was mysteriously failing a bunch of tests. **

## This PR does the following:

- Fixes the focus rectangle around the `TextInput` clear button so it is centered on both desktop and mobile views.

## How has this been tested?

- Locally in Storybook.

## Accessibility concerns or updates

- None.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
It looks good to me. Do you expect more tweaks to be done?

**Comment by oliviawongnyc** [comment]
> It looks good to me. Do you expect more tweaks to be done?

No, hopefully not, and apologies about all the emails you must have received, @EdwinGuzman. I couldn't trust what I was seeing locally so I kept pushing to be able to look at the Vercel preview.

**Comment by EdwinGuzman** [comment]
No worries, it's fine!

**Review by EdwinGuzman — APPROVED** [review]

**Review by bigfishdesign13 — APPROVED** [review]
Looks good!  Go ahead and merge this into `development` and we'll release it as part of `v1.5.4` on Thursday.  Thanks.

**Comment by bigfishdesign13** [comment]
@oliviawongnyc I just realized you can not merge branches right now, so I'll take care of the conflcits and then merge this branch into `development`.

**Pull request merged**
