### PR TITLE
Rename svg files to use underscores

### LINKED ISSUE #190: Rename `svg` files to use underscores instead of dashes
### Description of issue:
some svg files `arrow-xsmall.svg`, `search-small.svg` are named with a dash `-` but when imported by the svg inliner, a dash is not a valid character in a variable name, which means that the name passed into props should be using an underscore.  https://github.com/NYPL/nypl-design-system/blob/16d57cdc7345926e184db4f0441283dc6948a803/src/react-components/src/components/Icons/Icon.tsx#L4

To avoid confusion, let us rename the files themselves to use underscore.

### PR DESCRIPTION
**Pull request by adriana-alter**
Picked up a ticket (by way of taking a break from the really frustrating thing I was staring at!); hope this is okay!

Resolves https://github.com/NYPL/nypl-design-system/issues/190

### CODE REVIEW

**Review by helenvholmes — APPROVED** [review]
Git can be finnicky like that... this looks good to go!

**Comment by adriana-alter** [comment]
Great!  Should I go ahead and merge, or does everything require multiple approvals (even if it's really small)?

**Comment by hokei** [comment]
Nope!  Merge away @adriana-alter

**Comment by adriana-alter** [comment]
Um...the email notifications I got about deployment to Github Pages failing: does it just do that, or have I somehow broken your entire repo??? 
https://github.com/NYPL/nypl-design-system/actions/runs/202758430
https://github.com/NYPL/nypl-design-system/runs/967515037
Screen Shot 2020-08-11 at 12 55 37 PM

**Pull request merged**
