### PR TITLE
DSD-561: Adding new file type svg files for the Icon component

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes JIRA ticket [DSD-561](https://jira.nypl.org/browse/DSD-561)

## This PR does the following:
- Adds seven new svg files to use in the `Icon` component, specifically for the future `FileUploader` component.
- I'm not sure if I exported the SVG files correctly. There are some `stroke` and `fill` attributes that affect the `color` prop and the default `IconColors.UiBlack` makes the icon entirely black. So I had to add a check to change the color to white and this makes the seven new SVG icons to display correctly.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by bigfishdesign13** [comment]
@EdwinGuzman This looks good to me now.  Like we've done with other PRs, please take a look at the final changes I made.  If everything looks good, let me know and I will approve the PR.

**Comment by EdwinGuzman** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr757-zt5w91weixcnscw70odwsqtstpmajdik.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618591d9e368653808369e72

**Comment by EdwinGuzman** [comment]
@bigfishdesign13 Last update looks good 👍

**Review by bigfishdesign13 — APPROVED** [review]
Looks good.  This PR also covers [DSD-547](https://jira.nypl.org/browse/DSD-547).

**Pull request merged**
